[package]
name = "chipioindustries/remotes"
description = "A handler for RemoteEvent and RemoteFunction instances."
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs", "wally.exe"]

[dependencies]
Llama = "freddylist/llama@1.1.1"
Rapscallion = "chipioindustries/rapscallion@1.0.4"
Signal = "chipioindustries/signal@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"