[package]
name = "chipioindustries/signal"
description = "A Signal implementation that doesn't make use of BindableEvents."
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"